### ISSUE TITLE
The blog post about Python vs PHP is full of misinformation

### ISSUE THREAD

**Issue by davorminchorov** [bootdotdev/blog#38]
The following blog post https://blog.boot.dev/python/python-versus-php/ is full of useless information, written by someone who never really used PHP and favors Python.

Please do a bit more research or spend a few years working with PHP properly before you try to compare the two. 

Stop spreading misinformation for personal gain.

I can write the same blog post but change the language names and make Python the worst language ever, but there's nothing to gain from bashing languages with baseless claims.

**Comment by wagslane** [comment]
Thanks, I'll take a look at it soon.

**Comment by mabar** [comment]
> All of the kinds of attacks that Django helps protect you against are valid concerns when using raw PHP

This is still far from ideal. You wrote that Python is better for security, because framework built with it solves these problems. Compare PHP frameworks with raw Python and you will end up with exact opposite result.

I don't know Laravel but e.g. Nette offers all the protections listed in post and its template engine (Latte) offers even context-aware escaping. Only other lib I know which does that is Google Closure.
